[RunControl]
dataproducers  = ALPIDE_plane_0, ALPIDE_plane_1, APTS_2
loggers     = log
collectors  = dc
configs     = /home/eic/RICCARDO/altai/eudaq/user/altai/misc/conf/apts_testing.conf

[LibraryPaths]
# trigger_path = /home/user/trigger/software/

[LogCollector.log]
FILE_PATTERN = EUDAQLog$12D.log
# 0: DEBUG, 4: INFO, 5: WARN, 6: ERROR
LOG_LEVEL_WRITE = 0
LOG_LEVEL_PRINT = 1

[DataCollector.dc]
#dataproducers = ALPIDE_plane_0,ALPIDE_plane_1,ALPIDE_plane_2,ALPIDE_plane_3
dataproducers = ALPIDE_plane_0, ALPIDE_plane_1, APTS_2

[Producer.ALPIDE_plane_0]
serial      = DAQ-0009030300832631
plane       = 0
triggermode = primary

[Producer.ALPIDE_plane_1]
serial      = DAQ-0009042501141331
plane       = 1
triggermode = replica


[Producer.APTS_2]
serial      = DAQ-00090101054B1009
proximity   = APTS-003
plane       = 2
triggermode = replica
