[RunControl]
EUDAQ_CTRL_PRODUCER_LAST_START = ALPIDE_plane_0 # this is the one with the trigger primary
EUDAQ_CTRL_PRODUCER_FIRST_STOP = ALPIDE_plane_0
NEVENTS   = 50000

[Producer.ALPIDE_plane_0]
EUDAQ_DC      = dc
EUDAQ_ID      = 0
ITHR          = 50 #60
VCASN         = 55 #58
VCASN2        = 67 #70
VCLIP         = 0
IDB           = 29
STROBE_LENGTH = 400
# trg_type     = 1 # auto trigger

[Producer.ALPIDE_plane_1]
EUDAQ_DC      = dc
EUDAQ_ID      = 1
CHIPID        = 16
ITHR          = 60
VCASN         = 58
VCASN2        = 70
VCLIP         = 0
IDB           = 29
STROBE_LENGTH = 400 #5 us

[Producer.APTS_2]
EUDAQ_DC      = dc
EUDAQ_ID      = 2
# APTS settings
n_frames_before= 100
n_frames_after = 100
trg_type      = 0 # 0 = external, 1 = interal
# trg_thr       = 60 # 1 adc unit = 38.1 uV

# IBIASN = 500
# IBIASP = 45
# IBIAS3 = 850
# IBIAS4 = 2600
# IRESET = 1
# VRESET = 300 # to be changed with reverse bias and flavor
# VCASP  = 270
# VCASN  = 900

[DataCollector.dc]
#EUDAQ_MN = mon
EUDAQ_FW = native
EUDAQ_FW_PATTERN = /home/eic/RICCARDO/altai/eudaq/user/altai/misc/runs/run$6R_$12D$X #/dev/null/run$6R_$12D$X
#EUDAQ_FW_PATTERN = /home/user/DATA/run$6R_$12D$X #/dev/null/run$6R_$12D$X
#EUDAQ_DATACOL_SEND_MONITOR_FRACTION = 10


